language: haskell

before_install:
  - travis/cabal-apt-install $mode

install:
  - cabal configure -flib-Werror $mode
  - cabal build

script:
  - $script

env:
  - mode="--enable-tests" script="cabal test --show-details=always"
