#!/bin/sh -e

cabal configure -fstatic
cabal build
cd heroku
git rm -r *
cp ../dist/build/labyrinth-server/labyrinth-server .
cp -r ../public/ .
echo "web: ./labyrinth-server" > Procfile
touch requirements.txt
git add *
git commit -m "New version."
git push
cd - >/dev/null
